<?php

namespace ChallengesBundle\Repository;

/**
 * SimpleFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimpleFormRepository extends \Doctrine\ORM\EntityRepository
{
}
